/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonType } from "./components/ui-button/ui-button-types";
export namespace Components {
    interface UiButton {
        /**
          * Whether button should be disabled
         */
        "disabled": boolean;
        /**
          * Type of the button
         */
        "type"?: ButtonType;
    }
}
declare global {
    interface HTMLUiButtonElement extends Components.UiButton, HTMLStencilElement {
    }
    var HTMLUiButtonElement: {
        prototype: HTMLUiButtonElement;
        new (): HTMLUiButtonElement;
    };
    interface HTMLElementTagNameMap {
        "ui-button": HTMLUiButtonElement;
    }
}
declare namespace LocalJSX {
    interface UiButton {
        /**
          * Whether button should be disabled
         */
        "disabled"?: boolean;
        /**
          * Type of the button
         */
        "type"?: ButtonType;
    }
    interface IntrinsicElements {
        "ui-button": UiButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ui-button": LocalJSX.UiButton & JSXBase.HTMLAttributes<HTMLUiButtonElement>;
        }
    }
}
